modLoader="javafml"
loaderVersion="[35,)[36,)[37,)[38,)[39,)[40,)"
license="All rights reserved"
[[mods]]
modId="configurator"
version="1.2.0"
displayName="Configurator"
authors="Turing6"
logoFile= "Icon.png"
description='''
Library mod for creating custom JSON based config files
'''

[[dependencies.configurator]]
    modId="forge"
    mandatory=true
    versionRange="[35,)[36,)[37,)[38,)[39,)[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configurator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)[1.17,)[1.18,)"
    ordering="NONE"
    side="BOTH"
